create table tb_trabalhador (id int8 generated by default as identity, nome varchar(255), renda_diaria float8, primary key (id));
INSERT INTO tb_trabalhador (nome, renda_Diaria) VALUES ('Bob', 200.0);
INSERT INTO tb_trabalhador (nome, renda_Diaria) VALUES ('Maria', 300.0);
INSERT INTO tb_trabalhador (nome, renda_Diaria) VALUES ('Alex', 250.0);
