server:
  port: 8105

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://hr-eureka-server:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-folhaDePagamento
          uri:            lb://hr-folhadepagamento/pagamentos
          predicates:          - Path=/pagamentos/**
          
        - id: hr-trabalhador
          uri:            lb://hr-trabalhador/trabalhadores
          predicates:          - Path=/trabalhadores/**
          
        - id: hr-usuario
          uri:
            lb://hr-usuario/usuarios
          predicates:
          - Path=/usuarios/**
          
        - id: hr-oauth
          uri:
            lb://hr-oauth/oauth
          predicates:
          - Path=/oauth/**
          
        - id: hr-security
          uri:
            lb://hr-security/security
          predicates:
          - Path=/security/**
          
      default-filters:
        #Remove todos os cabeçalhos de solicitação confidenciais (Cookie, Set-Cookie e Autorização)
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        - RemoveRequestHeader=Authorization
          
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false

management:  endpoint:
    gateway:      enabled: true
      