server:
  port: 8105

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-folhaDePagamento
          uri:            lb://hr-folhadepagamento/pagamentos
          predicates:          - Path=/pagamentos/**
          
        - id: hr-trabalhador
          uri:            lb://hr-trabalhador/trabalhadores
          predicates:          - Path=/trabalhadores/**
          
        - id: hr-usuario
          uri:
            lb://hr-usuario/usuarios
          predicates:
          - Path=/usuarios/**
          
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false

management:  endpoint:
    gateway:      enabled: true
      